name: Python CI

# Trigger the workflow on any push to main branch or pull request

on:
    push:
       branches: 
            -  main 
    pull_request:
        branches:
            - main
    
jobs:
    test:
        runs-on: ubuntu-latest
        
        steps:
            - name: Set up python
              uses: actions/checkout@v2
              with:
                python-version: '3.8'
            
            # Step-3 Install dependencies
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            
            # Step-4 Run tests
            - name: Run tests
              run: pytest